### ISSUE TITLE
Can't build on GCC 14

### ISSUE THREAD

**Issue by lachesis** [openvenues/libpostal#677]
Hi!

I was checking out libpostal, and saw something that could be improved.

---
#### My country is USA

---
#### Here's how I'm using libpostal
I'm trying to canonicalize addresses.

---
#### Here's what I did
`make`

---
#### Here's what I got
```
$ make
make[2]: Entering directory '/home/user/projects/libpostal/libpostal/src'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.. -I/usr/local/include    -Wall -Wextra -Wno-unused-function -Wformat -Werror=format-security -Winit-self -Wno-sign-compare -DLIBPOSTAL_DATA_DIR='"/home/user/projects/libpostal/libpostal_data/libpostal"' -g -mfpmath=sse -msse2 -DUSE_SSE -g -O2 -O2 -D LIBPOSTAL_EXPORTS  -MT libpostal_la-libpostal.lo -MD -MP -MF .deps/libpostal_la-libpostal.Tpo -c -o libpostal_la-libpostal.lo `test -f 'libpostal.c' || echo './'`libpostal.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I.. -I/usr/local/include -Wall -Wextra -Wno-unused-function -Wformat -Werror=format-security -Winit-self -Wno-sign-compare -DLIBPOSTAL_DATA_DIR=\"/home/user/projects/libpostal/libpostal_data/libpostal\" -g -mfpmath=sse -msse2 -DUSE_SSE -g -O2 -O2 -D LIBPOSTAL_EXPORTS -MT libpostal_la-libpostal.lo -MD -MP -MF .deps/libpostal_la-libpostal.Tpo -c libpostal.c  -fPIC -DPIC -o .libs/libpostal_la-libpostal.o
libpostal.c: In function ‘libpostal_classify_language’:
libpostal.c:217:58: error: initialization of ‘libpostal_language_classifier_response_t *’ {aka ‘struct libpostal_language_classifier_response *’} from incompatible pointer type ‘language_classifier_response_t *’ {aka ‘struct language_classifier_response *’} [-Wincompatible-pointer-types]
  217 |     libpostal_language_classifier_response_t *response = classify_languages(address);
      |                                                          ^~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:1417: libpostal_la-libpostal.lo] Error 1
make[2]: Leaving directory '/home/user/projects/libpostal/libpostal/src'
make[1]: *** [Makefile:470: all-recursive] Error 1
make[1]: Leaving directory '/home/user/projects/libpostal/libpostal'
make: *** [Makefile:379: all] Error 2


$ gcc --version
gcc (GCC) 14.2.1 20240910
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

---
#### Here's what I was expecting
The package to build successfully.

---
#### For parsing issues, please answer "yes" or "no" to all that apply.

Does not apply.

---
#### Here's what I think could be improved

>GCC no longer allows implicitly casting all pointer types to all other pointer types. This behavior is now restricted to the void * type and its qualified variations. 

https://gcc.gnu.org/gcc-14/porting_to.html

Instead, libpostal should probably just export the other type.

**Comment by lachesis** [comment]
Alternatively, you could explicitly cast with a void* in the way:

```
    libpostal_language_classifier_response_t *response = (libpostal_language_classifier_response_t*)(void*)classify_languages(address);
```

**Comment by mikicz** [comment]
I managed a workaround, I updated  the Makefiles, updated `CFLAGS_BASE` to have `-Wno-incompatible-pointer-types` and that got me past that error

**Comment by aamirglb** [comment]
@lachesis, @mikicz  apart from the `incompatible pointer type` error, I also gets `implicit declaration of function` error for `strndup`

```
expand.c: In function 'expand_alternative_phrase_option':
expand.c:1502:36: error: implicit declaration of function 'strndup' [-Wimplicit-function-declaration]
 1502 |                 char *dupe_token = strndup(token + left_spaces, token_len - left_spaces - right_spaces);

numex.c: In function 'is_valid_roman_numeral':
numex.c:1216:18: error: implicit declaration of function 'strndup' [-Wimplicit-function-declaration]
 1216 |     char *copy = strndup(str, len);

```
To fix this issue, I manually #included `strndup.h` in those two files.

Did you get similar error while compiling the library?

My environment is MSYS2-MinGW64 with GCC 14.2.0

**Comment by mikicz** [comment]
Weirdly I didn't get that error!

**Comment by mikicz** [comment]
I'm on Linux (Fedora 41)

**Comment by aamirglb** [comment]
It looks like `strndup()` is a POSIX function and available on all POSIX platform but it is not supported on MSYS2/Windows.

**Comment by snowfoxsh** [comment]
I had the same issue. Updating `CFLAGS_BASE` to include `-Wno-incompatible-pointer-types`. I am on Arch Linux.

**Comment by albarrentine** [comment]
looks like this was introduced in PR #465 which redefined the language classifier's response struct in the API, kept the internal type, and then implicitly cast between them.

Refactored in #683 to just use the API type throughout, similar to how we handle parse_address. @lachesis can you try compiling that branch on GCC 14? I think compiler versions can be specified in the build matrix (via the CC env var) as well if anyone wants to add it to our Github Action.

**Comment by lachesis** [comment]
I was not able to build with that branch, with the same warning, but in a different place:

```bash
git clone https://github.com/openvenues/libpostal
git checkout lang_classifier_gcc14
./bootstrap.sh
./configure
make
```

```
gcc -DHAVE_CONFIG_H -I.. -I/usr/local/include    -Wall -Wextra -Wno-unused-function -Wformat -Werror=format-security -Winit-self -Wno-sign-compare -DLIBPOSTAL_DATA_DIR='"/usr/local/share/libpostal"' -g -mfpmath=sse -msse2 -DUSE_SSE -g -O2 -O3  -MT language_classifier_train-sparse_matrix_utils.o -MD -MP -MF .deps/language_classifier_train-sparse_matrix_utils.Tpo -c -o language_classifier_train-sparse_matrix_utils.o `test -f 'sparse_matrix_utils.c' || echo './'`sparse_matrix_utils.c
(... snip unrelated warning ...)
sparse_matrix_utils.c: In function ‘sparse_matrix_unique_columns’:
sparse_matrix_utils.c:100:50: error: passing argument 2 of ‘sparse_matrix_add_unique_columns’ from incompatible pointer type [-Wincompatible-pointer-types]
  100 |     if (sparse_matrix_add_unique_columns(matrix, unique_columns, ret)) {
      |                                                  ^~~~~~~~~~~~~~
      |                                                  |
      |                                                  kh_int_set_t *
```

However I think that's the only other place where there's an error. I have the following "patch" in my local branch:

```
diff --git a/src/libpostal.c b/src/libpostal.c
index 066a3015..4bdaeefd 100644
--- a/src/libpostal.c
+++ b/src/libpostal.c
@@ -214,7 +214,7 @@ libpostal_fuzzy_duplicate_status_t libpostal_is_street_duplicate_fuzzy(size_t nu
 }

 libpostal_language_classifier_response_t *libpostal_classify_language(char *address) {
-    libpostal_language_classifier_response_t *response = classify_languages(address);
+    libpostal_language_classifier_response_t *response = (libpostal_language_classifier_response_t*)(void*)classify_languages(address);

     if (response == NULL) {
         log_error("Language classification returned NULL\n");
diff --git a/src/sparse_matrix_utils.c b/src/sparse_matrix_utils.c
index 53fcaf97..53f1c3d6 100644
--- a/src/sparse_matrix_utils.c
+++ b/src/sparse_matrix_utils.c
@@ -97,7 +97,7 @@ uint32_array *sparse_matrix_unique_columns(sparse_matrix_t *matrix) {
     khash_t(int_set) *unique_columns = kh_init(int_set);
     uint32_array *ret = uint32_array_new();

-    if (sparse_matrix_add_unique_columns(matrix, unique_columns, ret)) {
+    if (sparse_matrix_add_unique_columns(matrix, (void*)unique_columns, ret)) {
         kh_destroy(int_set, unique_columns);
         return ret;
     }
```

My apologies for not calling out that location in the original ticket as well.

**Comment by albarrentine** [comment]
Ok pushed a second commit which just converts the type in that case to the correct type since the hash is created/destroyed entirely within the function. Didn't see any incompatible-pointer-types warnings on my end. Does that work for GCC 14?

**Comment by lachesis** [comment]
Yes, it builds cleanly now! Thanks for the help.

```
gcc (GCC) 14.2.1 20240910
```
